In [34]:
# iterating through a numpy array
import numpy as np

In [44]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
for row in a:
    print(row)
    for element in row:
        print(element, end=' ')
    print('\n\n')

[0 1 2 3]
0 1 2 3 


[4 5 6 7]
4 5 6 7 


[ 8  9 10 11]
8 9 10 11 


[12 13 14 15]
12 13 14 15 




In [37]:
# you can flatten an array into one dimension
for element in a.flatten():
    print(element, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [38]:
# numpy.nditer - Efficient multi-dimensional iterator object to iterate over arrays
# you pass in the array you want to iterate, and you can choose how to iterate it
for element in np.nditer(a, order='F'):
    print(element, end=' ')

0 4 8 12 1 5 9 13 2 6 10 14 3 7 11 15 

In [39]:
for element in np.nditer(a, order='F', flags=['external_loop']):
    print(element, end=' ')

[ 0  4  8 12] [ 1  5  9 13] [ 2  6 10 14] [ 3  7 11 15] 

In [40]:
for element in np.nditer(a, op_flags=['readwrite']):  # tells us operand will be read/written to
    element[...] = element * element  # this should square our numbers

In [42]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [49]:
b = np.arange(4).reshape(1,4)
b

array([[0, 1, 2, 3]])

In [45]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
# How do we iterate through two numpy arrays simultaneously?
# arrays need to be broadcastable:
# (1) shape is the same, or 
# (2) one of the dimensions of one is one
for x, y in np.nditer([a, b]): 
    print(x, y)  

0 0
1 1
2 2
3 3
4 0
5 1
6 2
7 3
8 0
9 1
10 2
11 3
12 0
13 1
14 2
15 3
